site_name: SQL Yandex Course
site_url: https://OREShake.github.io/sql_course/
theme:
  name: material

nav:
  - Шпаргалка: 'Шпаргалка.md'

  - Введение в базы данных:
      - Для чего нужна база данных: '01/01.md'
      - СУБД - великий библиотекарь: '01/02.md'
      - Язык запросов SQL: '01/03.md'
      - Первый запрос: '01/04.md'
      - Стиль запроса: '01/05.md'
      - Заключение: '01/06.md'

  - Срезы данных в SQL:
      - Как ограничить выборку: '02/01.md'
      - Типы данных в PostgreSQL: '02/02.md'
      - Изменение типов данных: '02/03.md'
      - Оператор WHERE. Операторы сравнения: '02/04.md'
      - Срез данных с помощью оператора WHERE: '02/05.md'
      - Как работать с диаграммой и описанием базы данных: '02/06.md'
      - Логические операторы: '02/07.md'
      - Срез данных с помощью логических операторов: '02/08.md'
      - Специальные операторы в условиях: '02/09.md'
      - Операторы IN, LIKE, BETWEEN: '02/10.md'
      - Функции для работы со строками: '02/11.md'
      - Применение функций для работы со строками: '02/12.md'
      - Операторы и функции для работы с датой и временем: '02/13.md'
      - Специальное значение NULL: '02/14.md'
      - Работа с пропусками: '02/15.md'
      - Условная конструкция с оператором CASE: '02/16.md'
      - Заключение: '02/17.md'

  - Агрегирующие функции. Группировка и сортировка данных:
    - Математические операции: '03/01.md'
    - Агрегирующие функции: '03/02.md'
    - Применение агрегирующих функций: '03/03.md'
    - Группировка данных: '03/04.md'
    - Применение оператора GROUP BY: '03/05.md'
    - Сортировка данных: '03/06.md'
    - Группировка и сортировка по нескольким полям: '03/07.md'
    - Оператор HAVING: '03/08.md'
    - Применение оператора HAVING: '03/09.md'
    - А как в реальной жизни: '03/10.md'
    - Заключение: '03/11.md'