site_name: SQL Yandex Course
site_url: https://OREShake.github.io/sql_course/
theme:
  name: material

nav:
  - Введение в базы данных:
      - Для чего нужна база данных: 'Введение в базы данных/01. Для чего нужна база данных.md'
      - СУБД - великий библиотекарь: 'Введение в базы данных/02. СУБД - великий библиотекарь.md'
      - Язык запросов SQL: 'Введение в базы данных/03. Язык запросов SQL.md'
      - Первый запрос: 'Введение в базы данных/04. Первый запрос.md'
      - Стиль запроса: 'Введение в базы данных/05. Стиль запроса.md'
      - Заключение: 'Введение в базы данных/06. Заключение.md'

  - Срезы данных в SQL:
      - Как ограничить выборку: 'Срезы данных в SQL/01. Как ограничить выборку.md'
      - Типы данных в PostgreSQL: 'Срезы данных в SQL/02. Типы данных в PostgreSQL.md'
      - Изменение типов данных: 'Срезы данных в SQL/03. Изменение типов данных.md'
      - Оператор WHERE. Операторы сравнения: 'Срезы данных в SQL/04. Оператор WHERE. Операторы сравнения.md'
      - Срез данных с помощью оператора WHERE: 'Срезы данных в SQL/05. Срез данных с помощью оператора WHERE.md'
      - Как работать с диаграммой и описанием базы данных: 'Срезы данных в SQL/06. Как работать с диаграммой и описанием базы данных.md'
      - Логические операторы: 'Срезы данных в SQL/07. Логические операторы.md'
      - Срез данных с помощью логических операторов: 'Срезы данных в SQL/08. Срез данных с помощью логических операторов.md'
      - Специальные операторы в условиях: 'Срезы данных в SQL/09. Специальные операторы в условиях.md'
      - Операторы IN, LIKE, BETWEEN: 'Срезы данных в SQL/10. Операторы IN, LIKE, BETWEEN.md'